[project]
name = "gridiron-warehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ayush Nair", email = "ayush.nair106@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dbt-snowflake>=1.12.1",
    "nflreadpy>=0.1.5",
    "polars>=1.44.2",
    "python-dotenv>=1.2.3",
    "snowflake-connector-python[pandas]>=4.7.3",
]

[project.scripts]
gridiron-warehouse = "gridiron_warehouse:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
